expertFinder/urls.py
from django.urls import path
from . import views

app_name = "expertFinder"

urlpatterns = [
    path("", views.index, name="search"),
    path("<int:pk>/", views.display_expert, name="display_expert"),
    path("search_results", views.search_results, name='search_results'),
    path("add", views.AddExpert.as_view(), name='add'),
    path("edit/<int:pk>", views.edit, name='edit'),
]
handler400 = 'expertFinder.error_handlers.bad_request'

project361/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # new
from django.urls import path, include # new
from django.conf.urls.static import static # new


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("expertFinder.urls")),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expertFinder/models.py
from django.db import models
from django.forms import ModelForm
from django.views.generic import ListView
from django.urls import reverse

# the great expert finder model!
class Expert(models.Model):
    firstName = models.CharField("First Name", max_length=55)
    lastName = models.CharField("Last Name", max_length=55)
    avatar = models.ImageField(upload_to='images/')
    organization = models.CharField(max_length=100)
    techSkills = models.TextField("Tech Skills")
    courseWork = models.TextField("OSU Course Work")
    gitRepo = models.URLField("Git Repo")
    linkedIn = models.URLField()
    twitter = models.URLField()
    email = models.EmailField()

    def __str__(self):
        return self.lastName

    def get_absolute_url(self):
        return reverse('expertFinder:display_expert', args=[self.id])

expertFinder/forms.py
from django import forms
from django.forms import modelformset_factory, ModelForm
from .models import Expert

DROP_DOWN_CHOICES = [
    ('name', 'Last Name'),
    ('skill', 'Skill'),
    ('class', 'Class'),
    ('organization', 'Organization')
]


class search_drop_down(forms.Form):
    search_by = forms.CharField(label='Search By', widget=forms.Select(choices=DROP_DOWN_CHOICES))
    search_term = forms.CharField(max_length=100, widget= forms.TextInput (attrs={'placeholder':'Enter text here'}))


class EditExpert(forms.ModelForm):
    class Meta:
        model = Expert
        fields = '__all__'

expertFinder/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from .models import Expert
from .forms import search_drop_down, EditExpert
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy

def index(request):
    search = search_drop_down()
    return render(request, "search.html", {
            "form": search
        })

def display_expert(request, pk):
    # pk is search string, want to search by last name (for now)
    expert = Expert.objects.get(pk=pk)
    results = {
        'expert': expert
    }
    return render(request, "display_expert.html", results)


def search_results(request):
    search_for = request.POST
    # POST returns dict value, need to search db by type for value specified, then
    # iterate through results, putting first+lastName into listbox and record ID

    form = None
    if search_for['search_by'] == 'name':
        query_results = Expert.objects.all().filter(lastName__contains=search_for['search_term'])
    if search_for['search_by'] == 'skill':
        query_results = Expert.objects.all().filter(techSkills__contains=search_for['search_term'])
    if search_for['search_by'] == 'class':
        query_results = Expert.objects.all().filter(courseWork__contains=search_for['search_term'])
    if search_for['search_by'] == 'organization':
        query_results = Expert.objects.all().filter(organization__contains=search_for['search_term'])

    # TODO handle no results, probably in search_results.html body
    results = {
        'query': query_results
    }

    return render(request, "search_results.html", results)

def edit(request, pk):
    try:
        data_to_edit = get_object_or_404(Expert, id= pk)
    except Exception:
        raise Http404('No entry')
    if request.method == 'POST':
        form = EditExpert(request.POST, instance=data_to_edit)

        if form.is_valid():
            form.save()
            return display_expert(request, pk)
    else:
        form = EditExpert(instance=data_to_edit)
        context = {
            'form': form
        }
        return render(request, 'editexpert.html', context)

class AddExpert(CreateView):
    model = Expert
    fields = ['firstName', 'lastName', 'avatar', 'organization', 'techSkills',
              'courseWork', 'gitRepo', 'linkedIn', 'twitter', 'email']
    template_name = 'expertFinder/expert_form.html'
    # success_url = reverse_lazy('expertFinder:search')

expertFinder/templates/display_expert.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
{{expert.lastName}}
{% endblock %}

{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/expertProfile.css' %}"/>
{% endblock %}

{% block body %}

    <h1>View Expert</h1>

    <ul>
        <div class="card" style="width: 80%;">
        <div class="card-body">
            <p class="card-text">
                <img class="expertPicture" src="{{ expert.avatar.url }}" width=120 height=120 alt="Expert profile picture">
                    <span class="card-text"><a href= {{ expert.gitRepo }} >
                        <img class="socialMedia" src="{% static 'images/github.png' %}" alt="Github icon">
                    </a></span>
                <br>
                    <span class="card-text"><a href= {{ expert.linkedIn }} >
                        <img class="socialMedia" src="{% static 'images/in.png' %}" alt="LinkedIn icon">
                    </a></span>
                <br>
                    <span class="card-text"><a href= {{ expert.twitter }}>
                        <img class="socialMedia" src="{% static 'images/twitter.png' %}" alt="Twitter icon">
                    </a></span>
                <br>
                    <span class="card-text"><a href= "mailto:"{{ expert.email }}>
                        <img class="socialMedia" src="{% static 'images/email.png' %}" alt="Email icon">
                    </a></span>
                </p>

           <h6 class="card-subtitle mb-2 text-muted">{{ expert.firstName}} {{ expert.lastName }}</h6>

            <div class="card" style="width: 80%;">
            <h5 class="card-title">Organization</h5>
           <h6 class="card-subtitle mb-2 text-muted">{{ expert.organization }}</h6>
            <h5 class="card-title">Tech Skills</h5>
           <h6 class="card-subtitle mb-2 text-muted">{{ expert.techSkills }}</h6>
            <h5 class="card-title">Course Work</h5>
           <h6 class="card-subtitle mb-2 text-muted">{{ expert.courseWork }}</h6>
            <br>
            </div>
            <a href="{% url 'expertFinder:edit' expert.id %}" class="btn btn-primary">Edit</a>
    </div>
</ul>

{% endblock %}

expertFinder/templates/editexpert.html
{% extends "layout.html" %}

{% block title %}
    Edit Expert
{% endblock %}

{% block body %}
    <h1>Edit Expert</h1>

    <ul>
       <div class="card">
           <div class="card-body" style="width: 80%">
               <form method="POST">
                  <fieldset>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Save</button>
                  </fieldset>
            </form>
           </div>
        </div>
    </ul>

{% endblock %}

expertFinder/templates/expertFinder/edit_expert.html
{% extends "layout.html" %}

{% block title %}
    Add Expert
{% endblock %}

{% block body %}
    <h1>Edit Expert</h1>

    <ul>
       <div class="card" style="width: 80%">
           <div class="card-body">
                <form  action="" method="POST" enctype="multipart/form-data">


                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary">

                </form>
            </div>
           </div>
    </ul>

{% endblock %}

expertFinder/templates/expertFinder/expert_form.html
{% extends "layout.html" %}

{% block title %}
    Add Expert
{% endblock %}

{% block body %}
    <h1>Add Expert</h1>

    <ul>
       <div class="card mb-2">
            <form method="POST" enctype="multipart/form-data">


                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save</button>

            </form>
        </div>
    </ul>

{% endblock %}

expertFinder/templates/expert_form.html
{% extends "layout.html" %}

{% block title %}
    Add Expert
{% endblock %}

{% block body %}
    <h1>Edit Expert</h1>

    <ul>
       <div class="card mb-2">
            <form method="POST">


                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary">Save</input>

            </form>
        </div>
    </ul>

{% endblock %}

expertFinder/templates/layout.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% block css %} {%  endblock %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="{% static 'styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}"/>

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark"  style="background-color: #d8741c;">
              <a class="navbar-brand" href="{% url 'expertFinder:search' %}"><img id="logoImage" src="{% static 'images/logo.png' %}" alt="ExpertFinder logo"></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                          <li class="nav-item active" class="underlined-nav">
                                <a class="nav-link" href="{% url 'expertFinder:search' %}">Search<span class="sr-only">(current)</span></a>
                          </li>
                          <li class="nav-item active" class="underlined-nav">
                                <a class="nav-link" href="{% url 'expertFinder:add' %}">Add User</a>
                          </li>
                    </ul>
              </div>
        </nav>

        <div class="row" id="mainBody">
            <div class="main col-lg-12 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

expertFinder/templates/navbar.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">        <link href="{% static 'styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}"/>

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark"  style="background-color: #d8741c;">
              <a class="navbar-brand" href="{% url 'expertFinder:search' %}"><img id="logoImage" src="{% static 'images/logo.png' %}" alt="My image"></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                          <li class="nav-item active" class="underlined-nav">
                                <a class="nav-link" href="{% url 'expertFinder:search' %}">Search<span class="sr-only">(current)</span></a>
                          </li>
                          <li class="nav-item active" class="underlined-nav">
                                <a class="nav-link" href="{% url 'expertFinder:add' %}">Add User</a>
                          </li>
                    </ul>
              </div>
        </nav>

        <div class="row" id="mainBody">
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

expertFinder/templates/search.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
Find Expert
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}"/>
{% endblock %}

{% block body %}
    <h1 class="headerCenter"><img id="mainLogo" src="{% static 'images/logo.png' %}" alt="Logo Image"></h1>
    <div class="center">
        <form action="{% url 'expertFinder:search_results' %}" method="POST" class="post-form">
            {% csrf_token %}

            <div>{{ form.as_p }}</div>
            <button type="submit" class="save btn btn-default" id="searchButton">Search</button>
        </form>
    </div>

{% endblock %}

expertFinder/templates/search_results.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
Search Results
{% endblock %}


{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/searchResults.css' %}"/>
{% endblock %}

{% block body %}

    <div id="searchBody">
        {% if query.exists %}

        <h1>Search Results</h1>

        <ul>
            {% for expert in query %}
                {% csrf_token %}
                <div class="card" style="width: 80%;">

                    <div id="floatContainer">

                        <div id="leftFloat">
                             <a href={% url 'expertFinder:display_expert' expert.id %}>
                                <img class="expertPicture" src="{{ expert.avatar.url }}" width=100 height=100 alt="Expert profile picture">
                             </a>
                       </div>

                       <div id="rightFloat">
                           <a href={% url 'expertFinder:display_expert' expert.id %}>
                               <h4><u>{{ expert.firstName.capitalize}} {{ expert.lastName.capitalize }}</u></h4>
                           </a>
                            <h6 class="card-subtitle mb-2 text-muted"><b>Organization:</b> {{ expert.organization }}</h6>
                            <span class="card-text"><a href= {{ expert.gitRepo }} >
                                <img class="socialMedia" src="{% static 'images/github.png' %}" alt="Github icon">
                            </a></span>
                            <span class="card-text"><a href= {{ expert.linkedIn }} >
                                <img class="socialMedia" src="{% static 'images/in.png' %}" alt="LinkedIn icon">
                            </a></span>
                            <span class="card-text"><a href= {{ expert.twitter }}>
                                <img class="socialMedia" src="{% static 'images/twitter.png' %}" alt="Twitter icon">
                            </a></span>
                            <span class="card-text"><a href= "mailto:"{{ expert.email }}>
                                <img class="socialMedia" src="{% static 'images/email.png' %}" alt="Email icon">
                            </a></span>
                        </div>
                    <div id="skills">
                        <div class="row">
                            <div class="col-sm-4">
                                <h5 class="card-title">Tech Skills</h5>
                                <h6 class="card-subtitle mb-2 text-muted">{{ expert.techSkills|slice:"0:50" }}</h6>
                            </div>
                            <div class="col-sm-4">
                                <h5 class="card-title">Course Work</h5>

                                <h6 class="card-subtitle mb-2 text-muted">{{ expert.courseWork|slice:"0:50" }}</h6>
                            </div>
                        </div>
                    </div>
                    </div>


                    <br>
                </div>
            </form>
            <br>

            {% endfor %}
        </ul>

            {% else %}
                <div id="noResults"> No results! Try another query.
                    <p> <a href="{% url 'expertFinder:search' %}" type="text/css"> <button id="backButton" type="button" class="btn btn-link">Back</button> </a> </p>
                </div>
            {% endif %}
    </div>

{% endblock %}